### ISSUE TITLE
External ITK Modules need to be updated to ITK 5.3.0.

### ISSUE THREAD

**Issue by Tarek-Alkabbani** [ntustison/ITKAdaptiveDenoising#14]
Hello Dr. Tustison

I was trying to use your module for one of my projects and it kept failing when trying to import it. Through searching around on github I believe that an update to ITK broke external modules. I have linked to the GitHub issue that refers to its issue as well as the solution which can be found at the end of the thread.

[https://github.com/InsightSoftwareConsortium/ITK/issues/3528](https://github.com/InsightSoftwareConsortium/ITK/issues/3528)

**Comment by ntustison** [comment]
Please post this over on the ITK discourse forum.  This issue isn't specific to this module.

**Comment by Tarek-Alkabbani** [comment]
While this issue is due to an ITK bug. The fix for it can only be implemented by the author of the Remote Modules 

This is the solution that the dev on the ITK forum gave. 
"Remote modules should update to ITK 5.3.0. See https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction for help with this"

From what I understand if you want the AdaptiveDenoising module to keep working with ITK, it needs to be rebuilt on the latest version of ITK.

**Comment by ntustison** [comment]
What your asking for seems to have already been done with [this commit](https://github.com/ntustison/ITKAdaptiveDenoising/commit/24825c8d246e941334f47968553f0ae388851f0c).

**Comment by Tarek-Alkabbani** [comment]
Okay, I see. I will investigate why it is still throwing the same error as if it has not been updated. I will see if the ITK forum can help. For now, I will close the issue. If I find that there is something else that needs to be done on this rep, I will re-open it with an update.
