### ISSUE TITLE
Publish Python package to PyPI

### ISSUE THREAD

**Issue by thewtex** [ntustison/ITKAdaptiveDenoising#6]
@ntustison can we [publish this to PyPI](https://itkpythonpackage.readthedocs.io/en/master/Build_ITK_Module_Python_packages.html#github-automated-ci-package-builds)? Happy to help with this.

**Comment by ntustison** [comment]
Sure, just let me know what I need to do.

**Comment by thewtex** [comment]
For the first time, download the wheels from the [CI](https://github.com/ntustison/ITKAdaptiveDenoising/actions/runs/478311177) and upload them with:

```
pip install twine
twine upload *.whl
```

For future releases, after [a PyPI token is added to the repository secrets](https://itkpythonpackage.readthedocs.io/en/master/Build_ITK_Module_Python_packages.html#github-automated-ci-package-builds), uploads are automatic after tagging the repository.

**Comment by ntustison** [comment]
Thanks @thewtex 

https://pypi.org/project/itk-adaptivedenoising/0.2.0/

**Comment by thewtex** [comment]
@ntustison awesome, thanks!
